### ISSUE TITLE
Why not use the same betas in SMPLDeformer and BodyModelParams?

### ISSUE THREAD

**Issue by Darius-H** [MoyGcc/vid2avatar#30]
https://github.com/MoyGcc/vid2avatar/blob/4c7e640200151e2210077459faac3e85e6b8a086/code/lib/model/v2a.py#L34C1-L38C74
I noticed that SMPLDeformer is initialized by the betas from the disk, which is the shape params after data preprocessing. But as in training procedure you use v2a_model.body_model_params to refine these params, why not use the same betas params in  SMPLDeformer and BodyModelParams?

**Comment by MoyGcc** [comment]
Hi, thank you for pointing this out. Yes, this is a bit problematic but simply using the refined betas is also not optimal because we don't update the betas used in SMPLDeformer https://github.com/MoyGcc/vid2avatar/blob/4c7e640200151e2210077459faac3e85e6b8a086/code/lib/model/v2a.py#L38 and networks are kinda overfitted to that betas which we load at the very beginning. 

I will try a version that updates the betas in SMPLDeformer during training and test with the refined betas. I think the results in that case are only marginally better than the current version (betas barely change). But thank you for raising this issue!
