### ISSUE TITLE
result mesh seems to be at the same place (NOT reaally an issue.)

### ISSUE THREAD

**Issue by carlosedubarreto** [MoyGcc/vid2avatar#8]
From the test I did, seems like the result is standing on the same place, but the video created with the result seems to have the movement of the person from the video.

Is there a way that I could export that movement information? I supose it would be the SMPL coeficients, right ?

thanks a lot for all the help.

**Comment by MoyGcc** [comment]
Yes, in the current version of this work, we always center the human according to the SMPL translation and the camera will be transformed accordingly which means the human position is indeed not correct in the global 3D space. This is because the initial camera and SMPL parameters are estimated by https://github.com/Arthur151/ROMP which does not provide a 3D correct perspective camera. I think even if you inverse the steps taken in `preprocessing/preprocessing.py`, we still cannot get a reasonable 3D movement (all demos are shown as projections into image space). 

One possible way to tackle this is for example using https://github.com/vye16/slahmr to get the global camera and SMPL trajectories and then do the preprocessing and scaling stuff. We're actually working on a project to better recover the global 3D movement which may come in the near future.

**Comment by carlosedubarreto** [comment]
Thanks a lot for all the information 🙏
